# Generated by Django 4.2.23 on 2025-07-24 01:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=10, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "creditos",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Créditos",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("inactiva", "Inactiva"),
                            ("en_revision", "En Revisión"),
                        ],
                        default="activa",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "profesor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materias_asignadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Profesor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Materia",
                "verbose_name_plural": "Materias",
                "db_table": "materias",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de fin")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("planificacion", "Planificación"),
                            ("inscripciones", "Inscripciones"),
                            ("en_curso", "En Curso"),
                            ("finalizado", "Finalizado"),
                        ],
                        default="planificacion",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Período",
                "verbose_name_plural": "Períodos",
                "db_table": "materias_periodos",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Prerrequisito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("obligatorio", "Obligatorio"),
                            ("recomendado", "Recomendado"),
                        ],
                        default="obligatorio",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerrequisitos",
                        to="materias.materia",
                        verbose_name="Materia",
                    ),
                ),
                (
                    "prerrequisito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materias_que_requieren",
                        to="materias.materia",
                        verbose_name="Prerrequisito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prerrequisito",
                "verbose_name_plural": "Prerrequisitos",
                "db_table": "materias_prerrequisitos",
                "ordering": ["materia", "prerrequisito"],
                "unique_together": {("materia", "prerrequisito")},
            },
        ),
    ]
