# Generated by Django 4.2.23 on 2025-07-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materias", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodo",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
    ]
