# Generated by Django 4.2.23 on 2025-07-24 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("bienvenida", "Bienvenida"),
                            ("inscripcion_exitosa", "Inscripción Exitosa"),
                            ("inscripcion_rechazada", "Inscripción Rechazada"),
                            ("calificacion_publicada", "Calificación Publicada"),
                            ("materia_asignada", "Materia Asignada"),
                            ("recordatorio", "Recordatorio"),
                            ("sistema", "Sistema"),
                            ("otro", "Otro"),
                        ],
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("mensaje", models.TextField(verbose_name="Mensaje")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("no_leida", "No Leída"),
                            ("leida", "Leída"),
                            ("archivada", "Archivada"),
                        ],
                        default="no_leida",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_lectura",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de lectura"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "db_table": "notificaciones",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "estado"],
                        name="notificacio_usuario_c3c835_idx",
                    ),
                    models.Index(
                        fields=["tipo", "fecha_creacion"],
                        name="notificacio_tipo_88f443_idx",
                    ),
                ],
            },
        ),
    ]
