# Generated by Django 4.2.23 on 2025-07-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notificaciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacion",
            name="leida",
            field=models.BooleanField(default=False, verbose_name="Leída"),
        ),
    ]
