# Generated by Django 4.2.23 on 2025-07-24 01:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("materias", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("aprobada", "Aprobada"),
                            ("reprobada", "Reprobada"),
                            ("retirada", "Retirada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="activa",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "nota_final",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="Nota Final",
                    ),
                ),
                (
                    "fecha_inscripcion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de inscripción"
                    ),
                ),
                (
                    "fecha_retiro",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de retiro"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        limit_choices_to={"role": "estudiante"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudiante",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones",
                        to="materias.materia",
                        verbose_name="Materia",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones",
                        to="materias.periodo",
                        verbose_name="Período",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripción",
                "verbose_name_plural": "Inscripciones",
                "db_table": "inscripciones",
                "ordering": ["-fecha_inscripcion"],
                "unique_together": {("estudiante", "materia", "periodo")},
            },
        ),
        migrations.CreateModel(
            name="Calificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("parcial_1", "Parcial 1"),
                            ("parcial_2", "Parcial 2"),
                            ("final", "Final"),
                            ("trabajo", "Trabajo"),
                            ("proyecto", "Proyecto"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Evaluación",
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="Nota",
                    ),
                ),
                (
                    "peso",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Peso (%)",
                    ),
                ),
                (
                    "comentarios",
                    models.TextField(blank=True, verbose_name="Comentarios"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calificaciones",
                        to="inscripciones.inscripcion",
                        verbose_name="Inscripción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calificación",
                "verbose_name_plural": "Calificaciones",
                "db_table": "inscripciones_calificaciones",
                "ordering": ["inscripcion", "tipo"],
                "unique_together": {("inscripcion", "tipo")},
            },
        ),
    ]
