# Generated by Django 4.2.23 on 2025-07-25 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inscripciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calificacion",
            name="fecha",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha"),
        ),
        migrations.AddField(
            model_name="calificacion",
            name="porcentaje",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Porcentaje",
            ),
        ),
        migrations.AlterField(
            model_name="calificacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("parcial", "Parcial"),
                    ("final", "Final"),
                    ("quiz", "Quiz"),
                    ("taller", "Taller"),
                    ("proyecto", "Proyecto"),
                    ("otro", "Otro"),
                ],
                max_length=20,
                verbose_name="Tipo de Evaluación",
            ),
        ),
    ]
