# Generated by Django 4.2.23 on 2025-07-25 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inscripciones", "0002_calificacion_fecha_calificacion_porcentaje_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calificacion",
            name="peso",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Peso (%)",
            ),
        ),
    ]
