# Generated by Django 4.2.23 on 2025-07-25 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inscripciones", "0004_alter_calificacion_nota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calificacion",
            name="nota",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="Nota",
            ),
        ),
    ]
