# Generated by Django 4.2.23 on 2025-07-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inscripciones", "0005_alter_calificacion_nota"),
    ]

    operations = [
        migrations.AddField(
            model_name="calificacion",
            name="descripcion",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
    ]
