# Generated by Django 4.2.23 on 2025-07-25 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inscripciones", "0006_calificacion_descripcion"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="calificacion",
            unique_together=set(),
        ),
    ]
