# Generated by Django 4.2.23 on 2025-07-24 01:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = []
