# Generated by Django 4.2.23 on 2025-07-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20250723_2024"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Departamento"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="identification",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Identificación"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="max_credits_per_semester",
            field=models.PositiveIntegerField(
                default=18, verbose_name="Máximo créditos por semestre"
            ),
        ),
    ]
