# Generated by Django 4.2.23 on 2025-07-24 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReporteGenerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("estudiante", "Reporte de Estudiante"),
                            ("profesor", "Reporte de Profesor"),
                            ("materia", "Reporte de Materia"),
                            ("periodo", "Reporte de Período"),
                            ("general", "Reporte General"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Reporte",
                    ),
                ),
                (
                    "nombre_archivo",
                    models.CharField(max_length=255, verbose_name="Nombre del Archivo"),
                ),
                (
                    "ruta_archivo",
                    models.CharField(max_length=500, verbose_name="Ruta del Archivo"),
                ),
                (
                    "parametros",
                    models.JSONField(
                        default=dict, verbose_name="Parámetros del Reporte"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("generando", "Generando"),
                            ("completado", "Completado"),
                            ("error", "Error"),
                            ("expirado", "Expirado"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "registros_procesados",
                    models.IntegerField(default=0, verbose_name="Registros Procesados"),
                ),
                (
                    "mensaje_error",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de Error"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "completado_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de completado"
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_solicitados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte Generado",
                "verbose_name_plural": "Reportes Generados",
                "db_table": "reportes_generados",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["solicitante", "tipo"],
                        name="reportes_ge_solicit_935e67_idx",
                    ),
                    models.Index(
                        fields=["estado", "created_at"],
                        name="reportes_ge_estado_50f8dd_idx",
                    ),
                ],
            },
        ),
    ]
