# Generated by Django 4.2.23 on 2025-07-25 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reportes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportegenerado",
            name="archivo_csv",
            field=models.FileField(
                blank=True, null=True, upload_to="reportes/", verbose_name="Archivo CSV"
            ),
        ),
        migrations.AddField(
            model_name="reportegenerado",
            name="generado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportes_generados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Generado por",
            ),
        ),
        migrations.AddField(
            model_name="reportegenerado",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reportes_usuario",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
    ]
