# Generated by Django 4.2.23 on 2025-07-25 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reportes", "0002_reportegenerado_archivo_csv_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportegenerado",
            name="solicitante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reportes_solicitados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Solicitante",
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reportes_usuario",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
    ]
