# Generated by Django 4.2.23 on 2025-07-25 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reportes", "0003_alter_reportegenerado_solicitante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportegenerado",
            name="fecha_generacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de generación"
            ),
        ),
        migrations.AlterField(
            model_name="reportegenerado",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reportes_usuario",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
    ]
